name: Deploy to ECS

on:
  push:
    branches:
      - development  # or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t testing-server .

      - name: Tag Docker image
        run: |
          docker tag testing-server:latest 230097452647.dkr.ecr.us-east-1.amazonaws.com/testing-server:latest

      - name: Push Docker image to ECR
        run: |
          docker push 230097452647.dkr.ecr.us-east-1.amazonaws.com/testing-server:latest

      - name: Force ECS service deployment
        run: |
          aws ecs update-service \
            --cluster favorable-kangaroo-zymf7l \
            --service someswar-task-new-3-service-i3iakrn3 \
            --force-new-deployment
